### ISSUE TITLE
[Epic ⚡] Event - create/edit/delete

### ISSUE THREAD

**Issue by Kevan-Y** [Eventhood/Eventhood-app#16]
## Stories

- [x] https://github.com/Eventhood/Eventhood-app/issues/17
- [x] https://github.com/Eventhood/Eventhood-app/issues/18
- [x] https://github.com/Eventhood/Eventhood-app/issues/19
- [x] https://github.com/Eventhood/Eventhood-app/issues/24
- [x] https://github.com/Eventhood/Eventhood-app/issues/71
- [x] https://github.com/Eventhood/Eventhood-app/issues/72
- [x] https://github.com/Eventhood/Eventhood-app/issues/73
- [x] https://github.com/Eventhood/Eventhood-app/issues/74
