### ISSUE TITLE
[Epic⚡] Search Functionality

### ISSUE THREAD

**Issue by cjustinn** [Eventhood/Eventhood-app#66]
## Stories
- [x] https://github.com/Eventhood/Eventhood-app/issues/63
- [x] https://github.com/Eventhood/Eventhood-app/issues/64
- [x] https://github.com/Eventhood/Eventhood-app/issues/65
- [x] https://github.com/Eventhood/Eventhood-app/issues/32
- [x] https://github.com/Eventhood/Eventhood-app/issues/35
