### ISSUE TITLE
[Epic⚡] Report Event

### ISSUE THREAD

**Issue by FMRashid** [Eventhood/Eventhood-app#67]
## Stories
- [ ] https://github.com/Eventhood/Eventhood-app/issues/69
- [ ] https://github.com/Eventhood/Eventhood-app/issues/70
- [ ] https://github.com/Eventhood/Eventhood-app/issues/75
